# Generated by Django 6.0.3 on 2026-04-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
