# Generated by Django 6.0.3 on 2026-04-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
