# Generated by Django 6.0.3 on 2026-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0002_remove_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_pdf',
            field=models.FileField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_video',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
