# Generated by Django 6.0.3 on 2026-04-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_currency_alter_product_price'),
        ('shop_bot', '0002_chatsession_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='product',
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('chat_id', models.BigIntegerField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('yangi', 'yangi'), ('oqildi', 'oʻqildi'), ('yakunlandi', 'yakunlandi')], default='yangi', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_notifications', to='product.product')),
            ],
            options={
                'verbose_name': 'Bot Xabarnomasi',
                'verbose_name_plural': 'Bot Xabarnomalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
