# Generated by Django 6.0.3 on 2026-04-26 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0003_alter_message_is_image_alter_message_is_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderchat',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('active', 'Jarayonda'), ('completed', 'Yakunlangan')], default='new', max_length=20),
        ),
    ]
