# Generated by Django 6.0.3 on 2026-04-20 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_brand_product_color_product_material_and_more'),
        ('shop_bot', '0004_telegramnotification_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Xaridor ismi')),
                ('chat_id', models.BigIntegerField(verbose_name='Telegram Chat ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('product_snapshot', models.JSONField(verbose_name="Mahsulot ma'lumotlari (snapshot)")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('answered', 'Javob berilgan'), ('closed', 'Yopilgan')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('is_from_customer', models.BooleanField(default=True, verbose_name='Xaridor yozganmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='shop_bot.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TelegramNotification',
        ),
    ]
