# Generated by Django 6.0.3 on 2026-04-26 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0004_message_owner_alter_orderchat_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchat',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_chats', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
