# Generated by Django 6.0.3 on 2026-04-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0005_chatsession_chatmessage_delete_telegramnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat xabari', 'verbose_name_plural': 'Chat xabarlari'},
        ),
    ]
