# Generated by Django 6.0.3 on 2026-04-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0006_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'verbose_name': 'Suhbat sessiyasi', 'verbose_name_plural': 'Suhbat sessiyalari'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram File ID'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fayl turi'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Xabar matni'),
        ),
    ]
