# Generated by Django 6.0.3 on 2026-04-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0006_orderchat_usage_link_alter_orderchat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
