# Generated by Django 6.0.3 on 2026-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0007_alter_chatmessage_options_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_id',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='vedio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='file_type',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
