# Generated by Django 6.0.3 on 2026-05-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0008_alter_message_options_message_file_message_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_pdf',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_video',
        ),
    ]
