# Generated by Django 6.0.3 on 2026-04-21 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0008_remove_chatmessage_file_id_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(upload_to='products/')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='vedio',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='username',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_from_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='product_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('jarayonda', 'Jarayonda'), ('yopilgan', 'Yopilgan')], default='yangi', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_bot.product'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='shop_bot.telegramuser'),
            preserve_default=False,
        ),
    ]
