# Generated by Django 6.0.3 on 2026-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_bot', '0009_product_telegramuser_alter_chatsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='tg_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
