# Generated by Django 6.0.3 on 2026-04-13 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_category_options_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to=settings.AUTH_USER_MODEL, verbose_name='Sotuvchi')),
            ],
            options={
                'verbose_name_plural': 'Usage',
                'db_table': 'usage',
                'ordering': ['-id'],
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='UsageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(max_length=500, verbose_name='Telegram havola')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='usage.usage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_links', to='product.category')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_categories', to='usage.usage')),
            ],
            options={
                'unique_together': {('category', 'usage')},
            },
        ),
    ]
